In [1]:
import sys

print(sys.executable)

c:\DataEngineeringProjects\pagepulse-books-web-scraping-pipeline\venv\Scripts\python.exe

#### Import the required libraries

#### PagePulse Books Web-Scraping ETL Pipeline

In [2]:
from __future__ import annotations

import json
import time
from datetime import datetime, timezone
from pathlib import Path
from urllib.parse import urljoin
from urllib.robotparser import RobotFileParser

import pandas as pd
import requests
from bs4 import BeautifulSoup
from dotenv import load_dotenv
from sqlalchemy import URL, create_engine, text

In [3]:
# Define the project path
PROJECT_ROOT = Path.cwd().parent

RAW_DATA_DIR = PROJECT_ROOT / "data" / "raw_data"
CLEANED_DATA_DIR = PROJECT_ROOT / "data" / "cleaned_data"
SCREENSHOTS_DIR = PROJECT_ROOT / "screenshots"
ENV_PATH = PROJECT_ROOT / ".env"

RAW_DATA_DIR.mkdir(parents=True, exist_ok=True)
CLEANED_DATA_DIR.mkdir(parents=True, exist_ok=True)
SCREENSHOTS_DIR.mkdir(parents=True, exist_ok=True)

print(PROJECT_ROOT)

c:\DataEngineeringProjects\pagepulse-books-web-scraping-pipeline

#### Define the Target Website

In [ ]:
BASE_URL = "https://books.toscrape.com/"
START_URL = "https://books.toscrape.com/catalogue/page-1.html"

print(START_URL)

# The catalogue page displays fictional book titles, prices, stock availability and ratings. 
# It is an appropriate practice source because the website itself identifies its content as a scraping demo

https://books.toscrape.com/catalogue/page-1.html

#### Check robots.txt

In [6]:
# The Robots Exclusion Protocol allows a website to publish crawling instructions in a robots.txt file.
# Python’s RobotFileParser can read those rules and answer whether a particular user agent may fetch a target URL.

import requests
from urllib.parse import urljoin
from urllib.robotparser import RobotFileParser

ROBOTS_URL = urljoin(BASE_URL, "robots.txt")

try:
    robots_response = requests.get(
        ROBOTS_URL,
        timeout=30
    )

    print("Robots URL:", ROBOTS_URL)
    print("HTTP status:", robots_response.status_code)

    if robots_response.status_code == 200:
        robot_parser = RobotFileParser()
        robot_parser.set_url(ROBOTS_URL)
        robot_parser.read()

        can_fetch = robot_parser.can_fetch(
            "PagePulseStudentBot/1.0",
            START_URL
        )

        crawl_delay = robot_parser.crawl_delay(
            "PagePulseStudentBot/1.0"
        )

        print("robots.txt file found.")
        print("Allowed to fetch target:", can_fetch)
        print("Crawl delay:", crawl_delay)

    elif robots_response.status_code == 404:
        print("No robots.txt file was published by the website.")
        print("No explicit crawling restrictions were found.")
        print(
            "Proceed responsibly using a polite delay "
            "between requests."
        )

    else:
        print(
            "The robots.txt file could not be assessed reliably."
        )
        print(
            "Do not assume scraping is permitted until "
            "the response is reviewed."
        )

except requests.RequestException as error:
    print("The robots.txt request failed.")
    print(error)

Robots URL: https://books.toscrape.com/robots.txt
HTTP status: 404
No robots.txt file was published by the website.
No explicit crawling restrictions were found.
Proceed responsibly using a polite delay between requests.

#### The Books to Scrape website does not currently publish a robots.txt file; requesting the expected robots.txt URL returns HTTP 404. Therefore, no explicit crawling restrictions or crawl-delay instructions are available. Since the website is designed for web-scraping practice, the project will proceed responsibly using a limited request rate and a delay between requests.

#### Before scraping any website, always check whether the site publishes a robots.txt file. This file contains the website's crawling guidelines and is part of responsible web scraping. Although the absence of a robots.txt file does not prevent scraping—as demonstrated by BooksToScrape—it is considered good practice to check for one before building any scraper

In [7]:
# First HTTP request to the target URL
HEADERS = {
    "User-Agent": (
        "PagePulseStudentBot/1.0 "
        "(educational web-scraping project)"
    )
}

session = requests.Session()
session.headers.update(HEADERS)

In [8]:
# First page request to the target URL
response = session.get(
    START_URL,
    timeout=30
)

print("Status code:", response.status_code)
print("Content type:", response.headers.get("Content-Type"))
print("HTML length:", len(response.text))

Status code: 200
Content type: text/html
HTML length: 50469

In [10]:
# Check for request errors
response.raise_for_status()

In [ ]:
# Inspect the first 1000 characters of the HTML response to verify that the page was retrieved successfully
print(response.text[:1000])

<!DOCTYPE html>
<!--[if lt IE 7]>      <html lang="en-us" class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>         <html lang="en-us" class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>         <html lang="en-us" class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!--> <html lang="en-us" class="no-js"> <!--<![endif]-->
    <head>
        <title>
    All products | Books to Scrape - Sandbox
</title>

        <meta http-equiv="content-type" content="text/html; charset=UTF-8" />
        <meta name="created" content="24th Jun 2016 09:30" />
        <meta name="description" content="" />
        <meta name="viewport" content="width=device-width" />
        <meta name="robots" content="NOARCHIVE,NOCACHE" />

        <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
        <!--[if lt IE 9]>
        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->


            <link rel="shortcut icon" href="../static/oscar/fav

#### Save the raw HTML.

In [12]:
# Do not clean the HTML before saving it. Raw data should represent what the source returned.

scraped_at = datetime.now(timezone.utc)

raw_html_path = RAW_DATA_DIR / (
    f"catalogue_page_1_{scraped_at:%Y%m%d_%H%M%S}.html"
)

raw_html_path.write_text(
    response.text,
    encoding="utf-8"
)

print("Raw HTML saved to:", raw_html_path)

Raw HTML saved to: c:\DataEngineeringProjects\pagepulse-books-web-scraping-pipeline\data\raw_data\catalogue_page_1_20260727_112329.html

#### Parse the page with BeautifulSoup

In [13]:
# Parsed document
soup = BeautifulSoup(
    response.text,
    "lxml"
)

In [14]:
# Inspect the page Title 
print(soup.title)
print(soup.title.get_text(strip=True))

<title>
    All products | Books to Scrape - Sandbox
</title>
All products | Books to Scrape - Sandbox

In [15]:
# Use prettify() only on a small section because the full page is long:
print(soup.article.prettify()[:1500])

<article class="product_pod">
 <div class="image_container">
  <a href="a-light-in-the-attic_1000/index.html">
   <img alt="A Light in the Attic" class="thumbnail" src="../media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/>
  </a>
 </div>
 <p class="star-rating Three">
  <i class="icon-star">
  </i>
  <i class="icon-star">
  </i>
  <i class="icon-star">
  </i>
  <i class="icon-star">
  </i>
  <i class="icon-star">
  </i>
 </p>
 <h3>
  <a href="a-light-in-the-attic_1000/index.html" title="A Light in the Attic">
   A Light in the ...
  </a>
 </h3>
 <div class="product_price">
  <p class="price_color">
   Â£51.77
  </p>
  <p class="instock availability">
   <i class="icon-ok">
   </i>
   In stock
  </p>
  <form>
   <button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">
    Add to basket
   </button>
  </form>
 </div>
</article>

#### Extract One Book

In [16]:
# Select the first book card 
first_book = soup.select_one("article.product_pod")

print(first_book)

<article class="product_pod">
<div class="image_container">
<a href="a-light-in-the-attic_1000/index.html"><img alt="A Light in the Attic" class="thumbnail" src="../media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg"/></a>
</div>
<p class="star-rating Three">
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
<i class="icon-star"></i>
</p>
<h3><a href="a-light-in-the-attic_1000/index.html" title="A Light in the Attic">A Light in the ...</a></h3>
<div class="product_price">
<p class="price_color">Â£51.77</p>
<p class="instock availability">
<i class="icon-ok"></i>

        In stock

</p>
<form>
<button class="btn btn-primary btn-block" data-loading-text="Adding..." type="submit">Add to basket</button>
</form>
</div>
</article>

Useful selectors include:

- Field	            Selector or location
- Book container    article.product_pod
- Title	            h3 a and its title attribute
- Price	            p.price_color
- Availability	    p.instock.availability
- Rating	        p.star-rating
- Product link	    h3 a[href]
- Image	            img.thumbnail[src]

In [17]:
# Extract the book title, price, and availability from the first book card 
title_element = first_book.select_one("h3 a")
price_element = first_book.select_one("p.price_color")
availability_element = first_book.select_one(
    "p.instock.availability"
)
rating_element = first_book.select_one("p.star-rating")
image_element = first_book.select_one("img.thumbnail")

title = title_element.get("title")
price_text = price_element.get_text(strip=True)
availability_text = availability_element.get_text(
    " ",
    strip=True
)

rating_classes = rating_element.get("class", [])
rating_text = next(
    (
        value
        for value in rating_classes
        if value != "star-rating"
    ),
    None
)

product_url = urljoin(
    START_URL,
    title_element.get("href")
)

image_url = urljoin(
    START_URL,
    image_element.get("src")
)

print("Title:", title)
print("Price:", price_text)
print("Availability:", availability_text)
print("Rating:", rating_text)
print("Product URL:", product_url)
print("Image URL:", image_url)

Title: A Light in the Attic
Price: Â£51.77
Availability: In stock
Rating: Three
Product URL: https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html
Image URL: https://books.toscrape.com/media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg

#### Extract all books from one page

In [19]:
def scrape_catalogue_page(
    page_url: str,
    session: requests.Session
) -> tuple[list[dict], str | None]:
    """Scrape all books and the next-page URL from one catalogue page."""

    response = session.get(
        page_url,
        timeout=30
    )
    response.raise_for_status()

    soup = BeautifulSoup(
        response.text,
        "lxml"
    )

    records: list[dict] = []

    for book in soup.select("article.product_pod"):
        title_element = book.select_one("h3 a")
        price_element = book.select_one("p.price_color")
        availability_element = book.select_one(
            "p.instock.availability"
        )
        rating_element = book.select_one("p.star-rating")
        image_element = book.select_one("img.thumbnail")

        rating_classes = (
            rating_element.get("class", [])
            if rating_element
            else []
        )

        rating_text = next(
            (
                value
                for value in rating_classes
                if value != "star-rating"
            ),
            None
        )

        record = {
            "title": (
                title_element.get("title")
                if title_element
                else None
            ),
            "price_raw": (
                price_element.get_text(strip=True)
                if price_element
                else None
            ),
            "availability_raw": (
                availability_element.get_text(" ", strip=True)
                if availability_element
                else None
            ),
            "rating_raw": rating_text,
            "product_url": (
                urljoin(
                    page_url,
                    title_element.get("href")
                )
                if title_element
                else None
            ),
            "image_url": (
                urljoin(
                    page_url,
                    image_element.get("src")
                )
                if image_element
                else None
            ),
            "source_page": page_url,
            "scraped_at": datetime.now(timezone.utc)
        }

        records.append(record)

    next_element = soup.select_one("li.next a")

    next_url = (
        urljoin(
            page_url,
            next_element.get("href")
        )
        if next_element
        else None
    )

    return records, next_url

In [20]:
# Test the function created above
page_one_records, next_page_url = scrape_catalogue_page(
    START_URL,
    session
)

print("Books extracted:", len(page_one_records))
print("Next page:", next_page_url)

Books extracted: 20
Next page: https://books.toscrape.com/catalogue/page-2.html

In [21]:
# Display one record 
page_one_records[0]

{'title': 'A Light in the Attic',
 'price_raw': 'Â£51.77',
 'availability_raw': 'In stock',
 'rating_raw': 'Three',
 'product_url': 'https://books.toscrape.com/catalogue/a-light-in-the-attic_1000/index.html',
 'image_url': 'https://books.toscrape.com/media/cache/2c/da/2cdad67c44b002e7ead0cc35693c0e8b.jpg',
 'source_page': 'https://books.toscrape.com/catalogue/page-1.html',
 'scraped_at': datetime.datetime(2026, 7, 27, 12, 35, 7, 96034, tzinfo=datetime.timezone.utc)}

#### Add Pagination

#### Pagination means that the catalogue is split across multiple pages. The next-page URL can be used to scrape the next page of results. The process can be repeated until there are no more pages left to scrape.
#### In simple terms,pagination is breaking up a large set of results into smaller, more manageable chunks that can be accessed one page at a time. This is often done to improve the user experience and reduce the load on the server.

In [22]:
# Limit the run to 3 pages while testing 
all_books: list[dict] = []

current_url = START_URL
maximum_pages = 3
page_number = 1

while current_url and page_number <= maximum_pages:
    print(f"Scraping page {page_number}: {current_url}")

    page_records, next_url = scrape_catalogue_page(
        current_url,
        session
    )

    all_books.extend(page_records)

    current_url = next_url
    page_number += 1

    time.sleep(1)

print("Total records:", len(all_books))

Scraping page 1: https://books.toscrape.com/catalogue/page-1.html
Scraping page 2: https://books.toscrape.com/catalogue/page-2.html
Scraping page 3: https://books.toscrape.com/catalogue/page-3.html
Total records: 60

#### Scrape all pages by removing the page limit

In [23]:
all_books = []
current_url = START_URL
page_number = 1

while current_url:
    print(f"Scraping page {page_number}")

    page_records, current_url = scrape_catalogue_page(
        current_url,
        session
    )

    all_books.extend(page_records)

    page_number += 1
    time.sleep(1)

print("Total records scraped:", len(all_books))

Scraping page 1
Scraping page 2
Scraping page 3
Scraping page 4
Scraping page 5
Scraping page 6
Scraping page 7
Scraping page 8
Scraping page 9
Scraping page 10
Scraping page 11
Scraping page 12
Scraping page 13
Scraping page 14
Scraping page 15
Scraping page 16
Scraping page 17
Scraping page 18
Scraping page 19
Scraping page 20
Scraping page 21
Scraping page 22
Scraping page 23
Scraping page 24
Scraping page 25
Scraping page 26
Scraping page 27
Scraping page 28
Scraping page 29
Scraping page 30
Scraping page 31
Scraping page 32
Scraping page 33
Scraping page 34
Scraping page 35
Scraping page 36
Scraping page 37
Scraping page 38
Scraping page 39
Scraping page 40
Scraping page 41
Scraping page 42
Scraping page 43
Scraping page 44
Scraping page 45
Scraping page 46
Scraping page 47
Scraping page 48
Scraping page 49
Scraping page 50
Total records scraped: 1000

#### The site currently presents 1,000 demo products across pages of 20 listings, so a complete extraction would produce approximately 1,000 records

#### Next: Convert the records into a DataFrame

In [24]:
books_raw = pd.DataFrame(all_books)
books_raw.head()

,title,price_raw,availability_raw,rating_raw,product_url,image_url,source_page,scraped_at
0,A Light in the Attic,Â£51.77,In stock,Three,https://books.toscrape.com/catalogue/a-light-i...,https://books.toscrape.com/media/cache/2c/da/2...,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00
1,Tipping the Velvet,Â£53.74,In stock,One,https://books.toscrape.com/catalogue/tipping-t...,https://books.toscrape.com/media/cache/26/0c/2...,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00
2,Soumission,Â£50.10,In stock,One,https://books.toscrape.com/catalogue/soumissio...,https://books.toscrape.com/media/cache/3e/ef/3...,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00
3,Sharp Objects,Â£47.82,In stock,Four,https://books.toscrape.com/catalogue/sharp-obj...,https://books.toscrape.com/media/cache/32/51/3...,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00
4,Sapiens: A Brief History of Humankind,Â£54.23,In stock,Five,https://books.toscrape.com/catalogue/sapiens-a...,https://books.toscrape.com/media/cache/be/a5/b...,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00

#### Inspect the structure of the DataFrame

In [25]:
books_raw.shape

(1000, 8)

In [26]:
books_raw.columns

Index(['title', 'price_raw', 'availability_raw', 'rating_raw', 'product_url',
       'image_url', 'source_page', 'scraped_at'],
      dtype='str')

In [27]:
books_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title             1000 non-null   str
 1   price_raw         1000 non-null   str
 2   availability_raw  1000 non-null   str
 3   rating_raw        1000 non-null   str
 4   product_url       1000 non-null   str
 5   image_url         1000 non-null   str
 6   source_page       1000 non-null   str
 7   scraped_at        1000 non-null   datetime64[us, UTC]
dtypes: datetime64[us, UTC](1), str(7)
memory usage: 62.6 KB

In [28]:
books_raw.isnull().sum()

title               0
price_raw           0
availability_raw    0
rating_raw          0
product_url         0
image_url           0
source_page         0
scraped_at          0
dtype: int64

In [29]:
books_raw.duplicated().sum()

np.int64(0)

#### Save the new raw csv dataset/dataframe by creating a timestamped raw csv

In [30]:
raw_csv_path = RAW_DATA_DIR / (
    f"books_raw_{scraped_at:%Y%m%d_%H%M%S}.csv"
)

books_raw.to_csv(
    raw_csv_path,
    index=False
)

print("Raw CSV saved to:", raw_csv_path)

Raw CSV saved to: c:\DataEngineeringProjects\pagepulse-books-web-scraping-pipeline\data\raw_data\books_raw_20260727_112329.csv

### Clean and transform the dataset

#### create a copy of the DataFrame to clean and transform the data

In [64]:
books_cleaned = books_raw.copy()

print(books_cleaned.shape)
books_cleaned

(1000, 8)

,title,price_raw,availability_raw,rating_raw,product_url,image_url,source_page,scraped_at
0,A Light in the Attic,Â£51.77,In stock,Three,https://books.toscrape.com/catalogue/a-light-i...,https://books.toscrape.com/media/cache/2c/da/2...,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00
1,Tipping the Velvet,Â£53.74,In stock,One,https://books.toscrape.com/catalogue/tipping-t...,https://books.toscrape.com/media/cache/26/0c/2...,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00
2,Soumission,Â£50.10,In stock,One,https://books.toscrape.com/catalogue/soumissio...,https://books.toscrape.com/media/cache/3e/ef/3...,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00
3,Sharp Objects,Â£47.82,In stock,Four,https://books.toscrape.com/catalogue/sharp-obj...,https://books.toscrape.com/media/cache/32/51/3...,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00
4,Sapiens: A Brief History of Humankind,Â£54.23,In stock,Five,https://books.toscrape.com/catalogue/sapiens-a...,https://books.toscrape.com/media/cache/be/a5/b...,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00
...,...,...,...,...,...,...,...,...
995,Alice in Wonderland (Alice's Adventures in Won...,Â£55.53,In stock,One,https://books.toscrape.com/catalogue/alice-in-...,https://books.toscrape.com/media/cache/96/ee/9...,https://books.toscrape.com/catalogue/page-50.html,2026-07-27 13:07:05.981122+00:00
996,"Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)",Â£57.06,In stock,Four,https://books.toscrape.com/catalogue/ajin-demi...,https://books.toscrape.com/media/cache/09/7c/0...,https://books.toscrape.com/catalogue/page-50.html,2026-07-27 13:07:05.982122+00:00
997,A Spy's Devotion (The Regency Spies of London #1),Â£16.97,In stock,Five,https://books.toscrape.com/catalogue/a-spys-de...,https://books.toscrape.com/media/cache/1b/5f/1...,https://books.toscrape.com/catalogue/page-50.html,2026-07-27 13:07:05.982122+00:00
998,1st to Die (Women's Murder Club #1),Â£53.98,In stock,One,https://books.toscrape.com/catalogue/1st-to-di...,https://books.toscrape.com/media/cache/2b/41/2...,https://books.toscrape.com/catalogue/page-50.html,2026-07-27 13:07:05.982122+00:00
999,"1,000 Places to See Before You Die",Â£26.08,In stock,Five,https://books.toscrape.com/catalogue/1000-plac...,https://books.toscrape.com/media/cache/d7/0f/d...,https://books.toscrape.com/catalogue/page-50.html,2026-07-27 13:07:05.983122+00:00

In [62]:
# Clean the Title column
books_cleaned["title"] = (
    books_cleaned["title"]
    .astype("string")
    .str.strip()
)

In [ ]:
# Clean the price column by removing the currency symbol and converting to numeric
books_cleaned["price_gbp"] = (
    books_cleaned["price_raw"]
    .astype("string")
    .str.replace(r"[^\d.]", "", regex=True)
    .str.strip()
)

books_cleaned["price_gbp"] = pd.to_numeric(
    books_cleaned["price_gbp"],
    errors="coerce"
)

In [76]:
books_cleaned

,title,price_raw,availability_raw,rating_raw,product_url,image_url,source_page,scraped_at,price_gbp,availability
0,A Light in the Attic,Â£51.77,In stock,Three,https://books.toscrape.com/catalogue/a-light-i...,https://books.toscrape.com/media/cache/2c/da/2...,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00,51.77,In Stock
1,Tipping the Velvet,Â£53.74,In stock,One,https://books.toscrape.com/catalogue/tipping-t...,https://books.toscrape.com/media/cache/26/0c/2...,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00,53.74,In Stock
2,Soumission,Â£50.10,In stock,One,https://books.toscrape.com/catalogue/soumissio...,https://books.toscrape.com/media/cache/3e/ef/3...,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00,50.1,In Stock
3,Sharp Objects,Â£47.82,In stock,Four,https://books.toscrape.com/catalogue/sharp-obj...,https://books.toscrape.com/media/cache/32/51/3...,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00,47.82,In Stock
4,Sapiens: A Brief History of Humankind,Â£54.23,In stock,Five,https://books.toscrape.com/catalogue/sapiens-a...,https://books.toscrape.com/media/cache/be/a5/b...,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00,54.23,In Stock
...,...,...,...,...,...,...,...,...,...,...
995,Alice in Wonderland (Alice's Adventures in Won...,Â£55.53,In stock,One,https://books.toscrape.com/catalogue/alice-in-...,https://books.toscrape.com/media/cache/96/ee/9...,https://books.toscrape.com/catalogue/page-50.html,2026-07-27 13:07:05.981122+00:00,55.53,In Stock
996,"Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)",Â£57.06,In stock,Four,https://books.toscrape.com/catalogue/ajin-demi...,https://books.toscrape.com/media/cache/09/7c/0...,https://books.toscrape.com/catalogue/page-50.html,2026-07-27 13:07:05.982122+00:00,57.06,In Stock
997,A Spy's Devotion (The Regency Spies of London #1),Â£16.97,In stock,Five,https://books.toscrape.com/catalogue/a-spys-de...,https://books.toscrape.com/media/cache/1b/5f/1...,https://books.toscrape.com/catalogue/page-50.html,2026-07-27 13:07:05.982122+00:00,16.97,In Stock
998,1st to Die (Women's Murder Club #1),Â£53.98,In stock,One,https://books.toscrape.com/catalogue/1st-to-di...,https://books.toscrape.com/media/cache/2b/41/2...,https://books.toscrape.com/catalogue/page-50.html,2026-07-27 13:07:05.982122+00:00,53.98,In Stock
999,"1,000 Places to See Before You Die",Â£26.08,In stock,Five,https://books.toscrape.com/catalogue/1000-plac...,https://books.toscrape.com/media/cache/d7/0f/d...,https://books.toscrape.com/catalogue/page-50.html,2026-07-27 13:07:05.983122+00:00,26.08,In Stock

In [74]:
# Clean availability 
books_cleaned["availability"] = (
    books_cleaned["availability_raw"]
    .astype("string")
    .str.replace(r"\s+", " ", regex=True)
    .str.strip()
    .str.title()
)

In [ ]:
# Convert ratings into numbers
rating_map = {
    "One": 1,
    "Two": 2,
    "Three": 3,
    "Four": 4,
    "Five": 5
}

books_cleaned["rating"] = (
    books_cleaned["rating_raw"]
    .map(rating_map)
    .astype("Int64")
)

In [79]:
books_cleaned

,title,price_raw,availability_raw,rating_raw,product_url,image_url,source_page,scraped_at,price_gbp,availability,rating
0,A Light in the Attic,Â£51.77,In stock,Three,https://books.toscrape.com/catalogue/a-light-i...,https://books.toscrape.com/media/cache/2c/da/2...,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00,51.77,In Stock,3
1,Tipping the Velvet,Â£53.74,In stock,One,https://books.toscrape.com/catalogue/tipping-t...,https://books.toscrape.com/media/cache/26/0c/2...,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00,53.74,In Stock,1
2,Soumission,Â£50.10,In stock,One,https://books.toscrape.com/catalogue/soumissio...,https://books.toscrape.com/media/cache/3e/ef/3...,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00,50.1,In Stock,1
3,Sharp Objects,Â£47.82,In stock,Four,https://books.toscrape.com/catalogue/sharp-obj...,https://books.toscrape.com/media/cache/32/51/3...,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00,47.82,In Stock,4
4,Sapiens: A Brief History of Humankind,Â£54.23,In stock,Five,https://books.toscrape.com/catalogue/sapiens-a...,https://books.toscrape.com/media/cache/be/a5/b...,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00,54.23,In Stock,5
...,...,...,...,...,...,...,...,...,...,...,...
995,Alice in Wonderland (Alice's Adventures in Won...,Â£55.53,In stock,One,https://books.toscrape.com/catalogue/alice-in-...,https://books.toscrape.com/media/cache/96/ee/9...,https://books.toscrape.com/catalogue/page-50.html,2026-07-27 13:07:05.981122+00:00,55.53,In Stock,1
996,"Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)",Â£57.06,In stock,Four,https://books.toscrape.com/catalogue/ajin-demi...,https://books.toscrape.com/media/cache/09/7c/0...,https://books.toscrape.com/catalogue/page-50.html,2026-07-27 13:07:05.982122+00:00,57.06,In Stock,4
997,A Spy's Devotion (The Regency Spies of London #1),Â£16.97,In stock,Five,https://books.toscrape.com/catalogue/a-spys-de...,https://books.toscrape.com/media/cache/1b/5f/1...,https://books.toscrape.com/catalogue/page-50.html,2026-07-27 13:07:05.982122+00:00,16.97,In Stock,5
998,1st to Die (Women's Murder Club #1),Â£53.98,In stock,One,https://books.toscrape.com/catalogue/1st-to-di...,https://books.toscrape.com/media/cache/2b/41/2...,https://books.toscrape.com/catalogue/page-50.html,2026-07-27 13:07:05.982122+00:00,53.98,In Stock,1
999,"1,000 Places to See Before You Die",Â£26.08,In stock,Five,https://books.toscrape.com/catalogue/1000-plac...,https://books.toscrape.com/media/cache/d7/0f/d...,https://books.toscrape.com/catalogue/page-50.html,2026-07-27 13:07:05.983122+00:00,26.08,In Stock,5

In [86]:
books_cleaned.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   title             1000 non-null   str
 1   price_raw         1000 non-null   str
 2   availability_raw  1000 non-null   str
 3   rating_raw        1000 non-null   str
 4   product_url       1000 non-null   str
 5   image_url         1000 non-null   str
 6   source_page       1000 non-null   str
 7   scraped_at        1000 non-null   datetime64[us, UTC]
 8   price_gbp         1000 non-null   Float64
 9   availability      1000 non-null   string
 10  rating            1000 non-null   Int64
dtypes: Float64(1), Int64(1), datetime64[us, UTC](1), str(7), string(1)
memory usage: 88.0 KB

In [85]:
# Convert the timestamp to a timezone-aware datetime object
books_cleaned["scraped_at"] = pd.to_datetime(
    books_cleaned["scraped_at"],
    utc=True,
    errors="coerce"
)

In [87]:
# Add the source domain as a new column
books_cleaned["source_website"] = "Books to Scrape"

In [96]:
books_cleaned

,title,price_gbp,availability,rating,product_url,image_url,source_website,source_page,scraped_at
0,A Light in the Attic,51.77,In Stock,3,https://books.toscrape.com/catalogue/a-light-i...,https://books.toscrape.com/media/cache/2c/da/2...,Books to Scrape,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00
1,Tipping the Velvet,53.74,In Stock,1,https://books.toscrape.com/catalogue/tipping-t...,https://books.toscrape.com/media/cache/26/0c/2...,Books to Scrape,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00
2,Soumission,50.1,In Stock,1,https://books.toscrape.com/catalogue/soumissio...,https://books.toscrape.com/media/cache/3e/ef/3...,Books to Scrape,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00
3,Sharp Objects,47.82,In Stock,4,https://books.toscrape.com/catalogue/sharp-obj...,https://books.toscrape.com/media/cache/32/51/3...,Books to Scrape,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00
4,Sapiens: A Brief History of Humankind,54.23,In Stock,5,https://books.toscrape.com/catalogue/sapiens-a...,https://books.toscrape.com/media/cache/be/a5/b...,Books to Scrape,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00
...,...,...,...,...,...,...,...,...,...
995,Alice in Wonderland (Alice's Adventures in Won...,55.53,In Stock,1,https://books.toscrape.com/catalogue/alice-in-...,https://books.toscrape.com/media/cache/96/ee/9...,Books to Scrape,https://books.toscrape.com/catalogue/page-50.html,2026-07-27 13:07:05.981122+00:00
996,"Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)",57.06,In Stock,4,https://books.toscrape.com/catalogue/ajin-demi...,https://books.toscrape.com/media/cache/09/7c/0...,Books to Scrape,https://books.toscrape.com/catalogue/page-50.html,2026-07-27 13:07:05.982122+00:00
997,A Spy's Devotion (The Regency Spies of London #1),16.97,In Stock,5,https://books.toscrape.com/catalogue/a-spys-de...,https://books.toscrape.com/media/cache/1b/5f/1...,Books to Scrape,https://books.toscrape.com/catalogue/page-50.html,2026-07-27 13:07:05.982122+00:00
998,1st to Die (Women's Murder Club #1),53.98,In Stock,1,https://books.toscrape.com/catalogue/1st-to-di...,https://books.toscrape.com/media/cache/2b/41/2...,Books to Scrape,https://books.toscrape.com/catalogue/page-50.html,2026-07-27 13:07:05.982122+00:00
999,"1,000 Places to See Before You Die",26.08,In Stock,5,https://books.toscrape.com/catalogue/1000-plac...,https://books.toscrape.com/media/cache/d7/0f/d...,Books to Scrape,https://books.toscrape.com/catalogue/page-50.html,2026-07-27 13:07:05.983122+00:00

In [104]:
# Create a separate formatted display column with the pound symbol to know the currency the book price is in. This is useful for display purposes, especially if the data is to be used in a dashboard or report.
books_cleaned["price_display"] = (
    "£" + books_cleaned["price_gbp"].map("{:.2f}".format)
)

In [106]:
books_cleaned.head()

,title,price_gbp,availability,rating,product_url,image_url,source_website,source_page,scraped_at,price_display
0,A Light in the Attic,51.77,In Stock,3,https://books.toscrape.com/catalogue/a-light-i...,https://books.toscrape.com/media/cache/2c/da/2...,Books to Scrape,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00,£51.77
1,Tipping the Velvet,53.74,In Stock,1,https://books.toscrape.com/catalogue/tipping-t...,https://books.toscrape.com/media/cache/26/0c/2...,Books to Scrape,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00,£53.74
2,Soumission,50.1,In Stock,1,https://books.toscrape.com/catalogue/soumissio...,https://books.toscrape.com/media/cache/3e/ef/3...,Books to Scrape,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00,£50.10
3,Sharp Objects,47.82,In Stock,4,https://books.toscrape.com/catalogue/sharp-obj...,https://books.toscrape.com/media/cache/32/51/3...,Books to Scrape,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00,£47.82
4,Sapiens: A Brief History of Humankind,54.23,In Stock,5,https://books.toscrape.com/catalogue/sapiens-a...,https://books.toscrape.com/media/cache/be/a5/b...,Books to Scrape,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00,£54.23

In [149]:
# Final columns 
# Columns to keep in the final cleaned dataset
books_cleaned = books_cleaned[
    [
        "title",
        "category",
        "price_gbp",
        "price_display",
        "availability",
        "rating",
        "product_url",
        "image_url",
        "source_website",
        "source_page",
        "scraped_at"
    ]
]

In [141]:
books_cleaned

,title,price_gbp,price_display,availability,rating,product_url,image_url,source_website,source_page,scraped_at,category
0,A Light in the Attic,51.77,£51.77,In Stock,3,https://books.toscrape.com/catalogue/a-light-i...,https://books.toscrape.com/media/cache/2c/da/2...,Books to Scrape,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00,Poetry
1,Tipping the Velvet,53.74,£53.74,In Stock,1,https://books.toscrape.com/catalogue/tipping-t...,https://books.toscrape.com/media/cache/26/0c/2...,Books to Scrape,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00,Historical Fiction
2,Soumission,50.1,£50.10,In Stock,1,https://books.toscrape.com/catalogue/soumissio...,https://books.toscrape.com/media/cache/3e/ef/3...,Books to Scrape,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00,Fiction
3,Sharp Objects,47.82,£47.82,In Stock,4,https://books.toscrape.com/catalogue/sharp-obj...,https://books.toscrape.com/media/cache/32/51/3...,Books to Scrape,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00,Mystery
4,Sapiens: A Brief History of Humankind,54.23,£54.23,In Stock,5,https://books.toscrape.com/catalogue/sapiens-a...,https://books.toscrape.com/media/cache/be/a5/b...,Books to Scrape,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00,History
...,...,...,...,...,...,...,...,...,...,...,...
995,Alice in Wonderland (Alice's Adventures in Won...,55.53,£55.53,In Stock,1,https://books.toscrape.com/catalogue/alice-in-...,https://books.toscrape.com/media/cache/96/ee/9...,Books to Scrape,https://books.toscrape.com/catalogue/page-50.html,2026-07-27 13:07:05.981122+00:00,Classics
996,"Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)",57.06,£57.06,In Stock,4,https://books.toscrape.com/catalogue/ajin-demi...,https://books.toscrape.com/media/cache/09/7c/0...,Books to Scrape,https://books.toscrape.com/catalogue/page-50.html,2026-07-27 13:07:05.982122+00:00,Sequential Art
997,A Spy's Devotion (The Regency Spies of London #1),16.97,£16.97,In Stock,5,https://books.toscrape.com/catalogue/a-spys-de...,https://books.toscrape.com/media/cache/1b/5f/1...,Books to Scrape,https://books.toscrape.com/catalogue/page-50.html,2026-07-27 13:07:05.982122+00:00,Historical Fiction
998,1st to Die (Women's Murder Club #1),53.98,£53.98,In Stock,1,https://books.toscrape.com/catalogue/1st-to-di...,https://books.toscrape.com/media/cache/2b/41/2...,Books to Scrape,https://books.toscrape.com/catalogue/page-50.html,2026-07-27 13:07:05.982122+00:00,Mystery
999,"1,000 Places to See Before You Die",26.08,£26.08,In Stock,5,https://books.toscrape.com/catalogue/1000-plac...,https://books.toscrape.com/media/cache/d7/0f/d...,Books to Scrape,https://books.toscrape.com/catalogue/page-50.html,2026-07-27 13:07:05.983122+00:00,Travel

In [144]:
print("Shape before dropna:", books_cleaned.shape)

books_cleaned.isna().sum()

Shape before dropna: (1000, 11)

title             0
category          0
price_gbp         0
price_display     0
availability      0
rating            0
product_url       0
image_url         0
source_website    0
source_page       0
scraped_at        0
dtype: int64

In [145]:
# Inspecting the critical columns for missing values
critical_columns = [
    "title",
    "category",
    "price_gbp",
    "price_display",
    "rating",
    "product_url",
    "scraped_at"
]

for column in critical_columns:
    print(
        column,
        "non-null rows:",
        books_cleaned[column].notna().sum(),
        "missing rows:",
        books_cleaned[column].isna().sum()
    )

title non-null rows: 1000 missing rows: 0
category non-null rows: 1000 missing rows: 0
price_gbp non-null rows: 1000 missing rows: 0
price_display non-null rows: 1000 missing rows: 0
rating non-null rows: 1000 missing rows: 0
product_url non-null rows: 1000 missing rows: 0
scraped_at non-null rows: 1000 missing rows: 0

In [ ]:
# Drop rows with missing values in critical columns
rows_before = len(books_cleaned)

books_cleaned = books_cleaned.dropna(
    subset=critical_columns
).reset_index(drop=True)

rows_after = len(books_cleaned)

print("Rows before:", rows_before)
print("Rows removed:", rows_before - rows_after)
print("Rows remaining:", rows_after)

Rows before: 1000
Rows removed: 0
Rows remaining: 1000

In [147]:
books_cleaned.head()

,title,category,price_gbp,price_display,availability,rating,product_url,image_url,source_website,source_page,scraped_at
0,A Light in the Attic,Poetry,51.77,£51.77,In Stock,3,https://books.toscrape.com/catalogue/a-light-i...,https://books.toscrape.com/media/cache/2c/da/2...,Books to Scrape,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00
1,Tipping the Velvet,Historical Fiction,53.74,£53.74,In Stock,1,https://books.toscrape.com/catalogue/tipping-t...,https://books.toscrape.com/media/cache/26/0c/2...,Books to Scrape,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00
2,Soumission,Fiction,50.1,£50.10,In Stock,1,https://books.toscrape.com/catalogue/soumissio...,https://books.toscrape.com/media/cache/3e/ef/3...,Books to Scrape,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00
3,Sharp Objects,Mystery,47.82,£47.82,In Stock,4,https://books.toscrape.com/catalogue/sharp-obj...,https://books.toscrape.com/media/cache/32/51/3...,Books to Scrape,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00
4,Sapiens: A Brief History of Humankind,History,54.23,£54.23,In Stock,5,https://books.toscrape.com/catalogue/sapiens-a...,https://books.toscrape.com/media/cache/be/a5/b...,Books to Scrape,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00

In [99]:
books_cleaned.duplicated().sum()

np.int64(0)

In [ ]:
# check the natural identifier column for duplicates
books_cleaned["product_url"].duplicated().sum()

np.int64(0)

#### Business-rule validation

In [116]:
# Check that all prices are greater than zero
print(
    "Invalid prices:",
    (~books_cleaned["price_gbp"].gt(0)).sum()
)

# Check that all ratings are between 1 and 5
print(
    "Invalid ratings:",
    (~books_cleaned["rating"].between(1, 5)).sum()
)

# Check for blank titles
print(
    "Blank titles:",
    books_cleaned["title"].str.strip().eq("").sum()
)

# Check that all product URLs start correctly
print(
    "Invalid product URLs:",
    (~books_cleaned["product_url"].str.startswith("https://")).sum()
)

Invalid prices: 0
Invalid ratings: 0
Blank titles: 0
Invalid product URLs: 0

In [148]:
books_cleaned

,title,category,price_gbp,price_display,availability,rating,product_url,image_url,source_website,source_page,scraped_at
0,A Light in the Attic,Poetry,51.77,£51.77,In Stock,3,https://books.toscrape.com/catalogue/a-light-i...,https://books.toscrape.com/media/cache/2c/da/2...,Books to Scrape,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00
1,Tipping the Velvet,Historical Fiction,53.74,£53.74,In Stock,1,https://books.toscrape.com/catalogue/tipping-t...,https://books.toscrape.com/media/cache/26/0c/2...,Books to Scrape,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00
2,Soumission,Fiction,50.1,£50.10,In Stock,1,https://books.toscrape.com/catalogue/soumissio...,https://books.toscrape.com/media/cache/3e/ef/3...,Books to Scrape,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00
3,Sharp Objects,Mystery,47.82,£47.82,In Stock,4,https://books.toscrape.com/catalogue/sharp-obj...,https://books.toscrape.com/media/cache/32/51/3...,Books to Scrape,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00
4,Sapiens: A Brief History of Humankind,History,54.23,£54.23,In Stock,5,https://books.toscrape.com/catalogue/sapiens-a...,https://books.toscrape.com/media/cache/be/a5/b...,Books to Scrape,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00
...,...,...,...,...,...,...,...,...,...,...,...
995,Alice in Wonderland (Alice's Adventures in Won...,Classics,55.53,£55.53,In Stock,1,https://books.toscrape.com/catalogue/alice-in-...,https://books.toscrape.com/media/cache/96/ee/9...,Books to Scrape,https://books.toscrape.com/catalogue/page-50.html,2026-07-27 13:07:05.981122+00:00
996,"Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)",Sequential Art,57.06,£57.06,In Stock,4,https://books.toscrape.com/catalogue/ajin-demi...,https://books.toscrape.com/media/cache/09/7c/0...,Books to Scrape,https://books.toscrape.com/catalogue/page-50.html,2026-07-27 13:07:05.982122+00:00
997,A Spy's Devotion (The Regency Spies of London #1),Historical Fiction,16.97,£16.97,In Stock,5,https://books.toscrape.com/catalogue/a-spys-de...,https://books.toscrape.com/media/cache/1b/5f/1...,Books to Scrape,https://books.toscrape.com/catalogue/page-50.html,2026-07-27 13:07:05.982122+00:00
998,1st to Die (Women's Murder Club #1),Mystery,53.98,£53.98,In Stock,1,https://books.toscrape.com/catalogue/1st-to-di...,https://books.toscrape.com/media/cache/2b/41/2...,Books to Scrape,https://books.toscrape.com/catalogue/page-50.html,2026-07-27 13:07:05.982122+00:00
999,"1,000 Places to See Before You Die",Travel,26.08,£26.08,In Stock,5,https://books.toscrape.com/catalogue/1000-plac...,https://books.toscrape.com/media/cache/d7/0f/d...,Books to Scrape,https://books.toscrape.com/catalogue/page-50.html,2026-07-27 13:07:05.983122+00:00

In [ ]:
required_columns = [
    "title",
    "price_gbp",
    "price_display",
    "availability",
    "rating",
    "product_url",
    "image_url",
    "source_website",
    "source_page",
    "scraped_at"
]

print("Dataset shape:", books_cleaned.shape)
print("\nMissing values:")
print(books_cleaned[required_columns].isna().sum())

print(
    "\nDuplicate product URLs:",
    books_cleaned["product_url"].duplicated().sum()
)

print(
    "Invalid prices:",
    (~books_cleaned["price_gbp"].gt(0)).sum()
)

print(
    "Invalid ratings:",
    (~books_cleaned["rating"].between(1, 5)).sum()
)

print(
    "Blank titles:",
    books_cleaned["title"].str.strip().eq("").sum()
)

print(
    "Invalid product URLs:",
    (~books_cleaned["product_url"].str.startswith("https://")).sum()
)

Dataset shape: (1000, 10)

Missing values:
title             0
price_gbp         0
availability      0
rating            0
product_url       0
image_url         0
source_website    0
source_page       0
scraped_at        0
dtype: int64

Duplicate product URLs: 0
Invalid prices: 0
Invalid ratings: 0
Blank titles: 0
Invalid product URLs: 0

In [118]:
books_cleaned.dtypes

title                             str
price_gbp                     Float64
price_display                     str
availability                   string
rating                          Int64
product_url                       str
image_url                         str
source_website                    str
source_page                       str
scraped_at        datetime64[us, UTC]
dtype: object

In [151]:
# Reusable Validation Function
def validate_books(dataframe: pd.DataFrame) -> None:
    """Validate the cleaned book-listing DataFrame."""

    required_columns = {
        "title",
        "category",
        "price_gbp",
        "price_display",
        "availability",
        "rating",
        "product_url",
        "source_website",
        "scraped_at"
    }

    missing_columns = required_columns - set(dataframe.columns)

    if missing_columns:
        raise ValueError(
            f"Missing columns: {sorted(missing_columns)}"
        )

    if dataframe.empty:
        raise ValueError("The cleaned DataFrame is empty.")

    if dataframe[list(required_columns)].isnull().any().any():
        raise ValueError(
            "Missing values exist in required columns."
        )

    if dataframe["product_url"].duplicated().any():
        raise ValueError("Duplicate product URLs exist.")

    if not dataframe["price_gbp"].gt(0).all():
        raise ValueError("One or more prices are invalid.")

    if not dataframe["rating"].between(1, 5).all():
        raise ValueError("One or more ratings are invalid.")

    print("Data validation successful.")

In [152]:
validate_books(books_cleaned)

Data validation successful.

#### Save the cleaned dataset

In [153]:
cleaned_csv_path = (
    CLEANED_DATA_DIR / "books_cleaned.csv"
)

books_cleaned.to_csv(
    cleaned_csv_path,
    index=False
)

print("Cleaned dataset saved to:", cleaned_csv_path)

Cleaned dataset saved to: c:\DataEngineeringProjects\pagepulse-books-web-scraping-pipeline\data\cleaned_data\books_cleaned.csv

In [154]:
# Check if the cleaned CSV file exists
cleaned_csv_path.exists()

True

In [155]:
books_check = pd.read_csv(cleaned_csv_path)

books_check.head()

,title,category,price_gbp,price_display,availability,rating,product_url,image_url,source_website,source_page,scraped_at
0,A Light in the Attic,Poetry,51.77,£51.77,In Stock,3,https://books.toscrape.com/catalogue/a-light-i...,https://books.toscrape.com/media/cache/2c/da/2...,Books to Scrape,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00
1,Tipping the Velvet,Historical Fiction,53.74,£53.74,In Stock,1,https://books.toscrape.com/catalogue/tipping-t...,https://books.toscrape.com/media/cache/26/0c/2...,Books to Scrape,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00
2,Soumission,Fiction,50.10,£50.10,In Stock,1,https://books.toscrape.com/catalogue/soumissio...,https://books.toscrape.com/media/cache/3e/ef/3...,Books to Scrape,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00
3,Sharp Objects,Mystery,47.82,£47.82,In Stock,4,https://books.toscrape.com/catalogue/sharp-obj...,https://books.toscrape.com/media/cache/32/51/3...,Books to Scrape,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00
4,Sapiens: A Brief History of Humankind,History,54.23,£54.23,In Stock,5,https://books.toscrape.com/catalogue/sapiens-a...,https://books.toscrape.com/media/cache/be/a5/b...,Books to Scrape,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00

#### Configure .env

In [156]:
# Load environment variables from the .env file
import os

load_dotenv(
    ENV_PATH,
    override=True
)

True

In [157]:
# Print the loaded environment variables to verify they are set correctly
print("User:", os.getenv("DB_USER"))
print("Host:", os.getenv("DB_HOST"))
print("Database:", os.getenv("DB_NAME"))
print(
    "Password loaded:",
    bool(os.getenv("DB_PASSWORD"))
)

User: postgres
Host: localhost
Database: pagepulse_books_db
Password loaded: True

#### Create PostgreSQL connection

In [158]:
# Database connection using SQLAlchemy
database_url = URL.create(
    drivername="postgresql+psycopg2",
    username=os.getenv("DB_USER"),
    password=os.getenv("DB_PASSWORD"),
    host=os.getenv("DB_HOST"),
    port=int(os.getenv("DB_PORT", "5432")),
    database=os.getenv("DB_NAME")
)

engine = create_engine(
    database_url,
    pool_pre_ping=True
)

print(engine)

Engine(postgresql+psycopg2://postgres:***@localhost:5432/pagepulse_books_db)

In [159]:
# This tests the connection to the database and retrieves some basic information about the current session.
with engine.connect() as connection:
    result = connection.execute(
        text(
            """
            SELECT
                current_database(),
                current_user,
                version();
            """
        )
    )

    print(result.fetchone())

('pagepulse_books_db', 'postgres', 'PostgreSQL 18.4 on x86_64-windows, compiled by msvc-19.44.35226, 64-bit')

#### Load Phase: Load the Cleaned Dataset into the database

In [161]:
rows_loaded = books_cleaned.to_sql(
    name="book_listings",
    con=engine,
    schema="public",
    if_exists="replace",
    index=False,
    method="multi",
    chunksize=500
)

print("Rows loaded:", rows_loaded)

Rows loaded: 1000

#### Verify the database load

In [162]:
database_count = pd.read_sql(
    """
    SELECT COUNT(*) AS total_rows
    FROM book_listings;
    """,
    con=engine
)

database_count

   total_rows
0        1000

#### Preview the Database Table

In [163]:
pd.read_sql(
    """
    SELECT *
    FROM book_listings
    LIMIT 10;
    """,
    con=engine
)

,title,category,price_gbp,price_display,availability,rating,product_url,image_url,source_website,source_page,scraped_at
0,A Light in the Attic,Poetry,51.77,£51.77,In Stock,3,https://books.toscrape.com/catalogue/a-light-i...,https://books.toscrape.com/media/cache/2c/da/2...,Books to Scrape,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00
1,Tipping the Velvet,Historical Fiction,53.74,£53.74,In Stock,1,https://books.toscrape.com/catalogue/tipping-t...,https://books.toscrape.com/media/cache/26/0c/2...,Books to Scrape,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00
2,Soumission,Fiction,50.10,£50.10,In Stock,1,https://books.toscrape.com/catalogue/soumissio...,https://books.toscrape.com/media/cache/3e/ef/3...,Books to Scrape,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00
3,Sharp Objects,Mystery,47.82,£47.82,In Stock,4,https://books.toscrape.com/catalogue/sharp-obj...,https://books.toscrape.com/media/cache/32/51/3...,Books to Scrape,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00
4,Sapiens: A Brief History of Humankind,History,54.23,£54.23,In Stock,5,https://books.toscrape.com/catalogue/sapiens-a...,https://books.toscrape.com/media/cache/be/a5/b...,Books to Scrape,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00
5,The Requiem Red,Young Adult,22.65,£22.65,In Stock,1,https://books.toscrape.com/catalogue/the-requi...,https://books.toscrape.com/media/cache/68/33/6...,Books to Scrape,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00
6,The Dirty Little Secrets of Getting Your Dream...,Business,33.34,£33.34,In Stock,4,https://books.toscrape.com/catalogue/the-dirty...,https://books.toscrape.com/media/cache/92/27/9...,Books to Scrape,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00
7,The Coming Woman: A Novel Based on the Life of...,Default,17.93,£17.93,In Stock,3,https://books.toscrape.com/catalogue/the-comin...,https://books.toscrape.com/media/cache/3d/54/3...,Books to Scrape,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00
8,The Boys in the Boat: Nine Americans and Their...,Default,22.60,£22.60,In Stock,4,https://books.toscrape.com/catalogue/the-boys-...,https://books.toscrape.com/media/cache/66/88/6...,Books to Scrape,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.530517+00:00
9,The Black Maria,Poetry,52.15,£52.15,In Stock,1,https://books.toscrape.com/catalogue/the-black...,https://books.toscrape.com/media/cache/58/46/5...,Books to Scrape,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.531656+00:00

#### Add product categories — The catalogue card does not directly display the book category. To obtain it, visit each product-detail page.

In [ ]:
# Get a sample of product URLs
sample_urls = books_cleaned["product_url"].head(5)

In [165]:
detail_response = session.get(
    sample_urls.iloc[0],
    timeout=30
)
detail_response.raise_for_status()

detail_soup = BeautifulSoup(
    detail_response.text,
    "lxml"
)

detail_soup.select("ul.breadcrumb li")

[<li>
 <a href="../../index.html">Home</a>
 </li>,
 <li>
 <a href="../category/books_1/index.html">Books</a>
 </li>,
 <li>
 <a href="../category/books/poetry_23/index.html">Poetry</a>
 </li>,
 <li class="active">A Light in the Attic</li>]

In [136]:
breadcrumb_items = detail_soup.select(
    "ul.breadcrumb li"
)

category = (
    breadcrumb_items[2].get_text(strip=True)
    if len(breadcrumb_items) >= 3
    else None
)

print(category)

Poetry

In [137]:
def scrape_book_category(
    product_url: str,
    session: requests.Session
) -> str | None:
    """Extract the category from a product-detail page."""

    response = session.get(
        product_url,
        timeout=30
    )
    response.raise_for_status()

    soup = BeautifulSoup(
        response.text,
        "lxml"
    )

    breadcrumb_items = soup.select(
        "ul.breadcrumb li"
    )

    if len(breadcrumb_items) < 3:
        return None

    return breadcrumb_items[2].get_text(strip=True)

In [138]:
print(
    scrape_book_category(
        books_cleaned.loc[0, "product_url"],
        session
    )
)

Poetry

In [139]:
categories = []

for index, product_url in enumerate(
    books_cleaned["product_url"],
    start=1
):
    print(f"Category {index} of {len(books_cleaned)}")

    category = scrape_book_category(
        product_url,
        session
    )

    categories.append(category)
    time.sleep(0.5)

books_cleaned["category"] = categories

Category 1 of 1000
Category 2 of 1000
Category 3 of 1000
Category 4 of 1000
Category 5 of 1000
Category 6 of 1000
Category 7 of 1000
Category 8 of 1000
Category 9 of 1000
Category 10 of 1000
Category 11 of 1000
Category 12 of 1000
Category 13 of 1000
Category 14 of 1000
Category 15 of 1000
Category 16 of 1000
Category 17 of 1000
Category 18 of 1000
Category 19 of 1000
Category 20 of 1000
Category 21 of 1000
Category 22 of 1000
Category 23 of 1000
Category 24 of 1000
Category 25 of 1000
Category 26 of 1000
Category 27 of 1000
Category 28 of 1000
Category 29 of 1000
Category 30 of 1000
Category 31 of 1000
Category 32 of 1000
Category 33 of 1000
Category 34 of 1000
Category 35 of 1000
Category 36 of 1000
Category 37 of 1000
Category 38 of 1000
Category 39 of 1000
Category 40 of 1000
Category 41 of 1000
Category 42 of 1000
Category 43 of 1000
Category 44 of 1000
Category 45 of 1000
Category 46 of 1000
Category 47 of 1000
Category 48 of 1000
Category 49 of 1000
Category 50 of 1000
Category 51 of 1000
Category 52 of 1000
Category 53 of 1000
Category 54 of 1000
Category 55 of 1000
Category 56 of 1000
Category 57 of 1000
Category 58 of 1000
Category 59 of 1000
Category 60 of 1000
Category 61 of 1000
Category 62 of 1000
Category 63 of 1000
Category 64 of 1000
Category 65 of 1000
Category 66 of 1000
Category 67 of 1000
Category 68 of 1000
Category 69 of 1000
Category 70 of 1000
Category 71 of 1000
Category 72 of 1000
Category 73 of 1000
Category 74 of 1000
Category 75 of 1000
Category 76 of 1000
Category 77 of 1000
Category 78 of 1000
Category 79 of 1000
Category 80 of 1000
Category 81 of 1000
Category 82 of 1000
Category 83 of 1000
Category 84 of 1000
Category 85 of 1000
Category 86 of 1000
Category 87 of 1000
Category 88 of 1000
Category 89 of 1000
Category 90 of 1000
Category 91 of 1000
Category 92 of 1000
Category 93 of 1000
Category 94 of 1000
Category 95 of 1000
Category 96 of 1000
Category 97 of 1000
Category 98 of 1000
Category 99 of 1000
Category 100 of 1000
Category 101 of 1000
Category 102 of 1000
Category 103 of 1000
Category 104 of 1000
Category 105 of 1000
Category 106 of 1000
Category 107 of 1000
Category 108 of 1000
Category 109 of 1000
Category 110 of 1000
Category 111 of 1000
Category 112 of 1000
Category 113 of 1000
Category 114 of 1000
Category 115 of 1000
Category 116 of 1000
Category 117 of 1000
Category 118 of 1000
Category 119 of 1000
Category 120 of 1000
Category 121 of 1000
Category 122 of 1000
Category 123 of 1000
Category 124 of 1000
Category 125 of 1000
Category 126 of 1000
Category 127 of 1000
Category 128 of 1000
Category 129 of 1000
Category 130 of 1000
Category 131 of 1000
Category 132 of 1000
Category 133 of 1000
Category 134 of 1000
Category 135 of 1000
Category 136 of 1000
Category 137 of 1000
Category 138 of 1000
Category 139 of 1000
Category 140 of 1000
Category 141 of 1000
Category 142 of 1000
Category 143 of 1000
Category 144 of 1000
Category 145 of 1000
Category 146 of 1000
Category 147 of 1000
Category 148 of 1000
Category 149 of 1000
Category 150 of 1000
Category 151 of 1000
Category 152 of 1000
Category 153 of 1000
Category 154 of 1000
Category 155 of 1000
Category 156 of 1000
Category 157 of 1000
Category 158 of 1000
Category 159 of 1000
Category 160 of 1000
Category 161 of 1000
Category 162 of 1000
Category 163 of 1000
Category 164 of 1000
Category 165 of 1000
Category 166 of 1000
Category 167 of 1000
Category 168 of 1000
Category 169 of 1000
Category 170 of 1000
Category 171 of 1000
Category 172 of 1000
Category 173 of 1000
Category 174 of 1000
Category 175 of 1000
Category 176 of 1000
Category 177 of 1000
Category 178 of 1000
Category 179 of 1000
Category 180 of 1000
Category 181 of 1000
Category 182 of 1000
Category 183 of 1000
Category 184 of 1000
Category 185 of 1000
Category 186 of 1000
Category 187 of 1000
Category 188 of 1000
Category 189 of 1000
Category 190 of 1000
Category 191 of 1000
Category 192 of 1000
Category 193 of 1000
Category 194 of 1000
Category 195 of 1000
Category 196 of 1000
Category 197 of 1000
Category 198 of 1000
Category 199 of 1000
Category 200 of 1000
Category 201 of 1000
Category 202 of 1000
Category 203 of 1000
Category 204 of 1000
Category 205 of 1000
Category 206 of 1000
Category 207 of 1000
Category 208 of 1000
Category 209 of 1000
Category 210 of 1000
Category 211 of 1000
Category 212 of 1000
Category 213 of 1000
Category 214 of 1000
Category 215 of 1000
Category 216 of 1000
Category 217 of 1000
Category 218 of 1000
Category 219 of 1000
Category 220 of 1000
Category 221 of 1000
Category 222 of 1000
Category 223 of 1000
Category 224 of 1000
Category 225 of 1000
Category 226 of 1000
Category 227 of 1000
Category 228 of 1000
Category 229 of 1000
Category 230 of 1000
Category 231 of 1000
Category 232 of 1000
Category 233 of 1000
Category 234 of 1000
Category 235 of 1000
Category 236 of 1000
Category 237 of 1000
Category 238 of 1000
Category 239 of 1000
Category 240 of 1000
Category 241 of 1000
Category 242 of 1000
Category 243 of 1000
Category 244 of 1000
Category 245 of 1000
Category 246 of 1000
Category 247 of 1000
Category 248 of 1000
Category 249 of 1000
Category 250 of 1000
Category 251 of 1000
Category 252 of 1000
Category 253 of 1000
Category 254 of 1000
Category 255 of 1000
Category 256 of 1000
Category 257 of 1000
Category 258 of 1000
Category 259 of 1000
Category 260 of 1000
Category 261 of 1000
Category 262 of 1000
Category 263 of 1000
Category 264 of 1000
Category 265 of 1000
Category 266 of 1000
Category 267 of 1000
Category 268 of 1000
Category 269 of 1000
Category 270 of 1000
Category 271 of 1000
Category 272 of 1000
Category 273 of 1000
Category 274 of 1000
Category 275 of 1000
Category 276 of 1000
Category 277 of 1000
Category 278 of 1000
Category 279 of 1000
Category 280 of 1000
Category 281 of 1000
Category 282 of 1000
Category 283 of 1000
Category 284 of 1000
Category 285 of 1000
Category 286 of 1000
Category 287 of 1000
Category 288 of 1000
Category 289 of 1000
Category 290 of 1000
Category 291 of 1000
Category 292 of 1000
Category 293 of 1000
Category 294 of 1000
Category 295 of 1000
Category 296 of 1000
Category 297 of 1000
Category 298 of 1000
Category 299 of 1000
Category 300 of 1000
Category 301 of 1000
Category 302 of 1000
Category 303 of 1000
Category 304 of 1000
Category 305 of 1000
Category 306 of 1000
Category 307 of 1000
Category 308 of 1000
Category 309 of 1000
Category 310 of 1000
Category 311 of 1000
Category 312 of 1000
Category 313 of 1000
Category 314 of 1000
Category 315 of 1000
Category 316 of 1000
Category 317 of 1000
Category 318 of 1000
Category 319 of 1000
Category 320 of 1000
Category 321 of 1000
Category 322 of 1000
Category 323 of 1000
Category 324 of 1000
Category 325 of 1000
Category 326 of 1000
Category 327 of 1000
Category 328 of 1000
Category 329 of 1000
Category 330 of 1000
Category 331 of 1000
Category 332 of 1000
Category 333 of 1000
Category 334 of 1000
Category 335 of 1000
Category 336 of 1000
Category 337 of 1000
Category 338 of 1000
Category 339 of 1000
Category 340 of 1000
Category 341 of 1000
Category 342 of 1000
Category 343 of 1000
Category 344 of 1000
Category 345 of 1000
Category 346 of 1000
Category 347 of 1000
Category 348 of 1000
Category 349 of 1000
Category 350 of 1000
Category 351 of 1000
Category 352 of 1000
Category 353 of 1000
Category 354 of 1000
Category 355 of 1000
Category 356 of 1000
Category 357 of 1000
Category 358 of 1000
Category 359 of 1000
Category 360 of 1000
Category 361 of 1000
Category 362 of 1000
Category 363 of 1000
Category 364 of 1000
Category 365 of 1000
Category 366 of 1000
Category 367 of 1000
Category 368 of 1000
Category 369 of 1000
Category 370 of 1000
Category 371 of 1000
Category 372 of 1000
Category 373 of 1000
Category 374 of 1000
Category 375 of 1000
Category 376 of 1000
Category 377 of 1000
Category 378 of 1000
Category 379 of 1000
Category 380 of 1000
Category 381 of 1000
Category 382 of 1000
Category 383 of 1000
Category 384 of 1000
Category 385 of 1000
Category 386 of 1000
Category 387 of 1000
Category 388 of 1000
Category 389 of 1000
Category 390 of 1000
Category 391 of 1000
Category 392 of 1000
Category 393 of 1000
Category 394 of 1000
Category 395 of 1000
Category 396 of 1000
Category 397 of 1000
Category 398 of 1000
Category 399 of 1000
Category 400 of 1000
Category 401 of 1000
Category 402 of 1000
Category 403 of 1000
Category 404 of 1000
Category 405 of 1000
Category 406 of 1000
Category 407 of 1000
Category 408 of 1000
Category 409 of 1000
Category 410 of 1000
Category 411 of 1000
Category 412 of 1000
Category 413 of 1000
Category 414 of 1000
Category 415 of 1000
Category 416 of 1000
Category 417 of 1000
Category 418 of 1000
Category 419 of 1000
Category 420 of 1000
Category 421 of 1000
Category 422 of 1000
Category 423 of 1000
Category 424 of 1000
Category 425 of 1000
Category 426 of 1000
Category 427 of 1000
Category 428 of 1000
Category 429 of 1000
Category 430 of 1000
Category 431 of 1000
Category 432 of 1000
Category 433 of 1000
Category 434 of 1000
Category 435 of 1000
Category 436 of 1000
Category 437 of 1000
Category 438 of 1000
Category 439 of 1000
Category 440 of 1000
Category 441 of 1000
Category 442 of 1000
Category 443 of 1000
Category 444 of 1000
Category 445 of 1000
Category 446 of 1000
Category 447 of 1000
Category 448 of 1000
Category 449 of 1000
Category 450 of 1000
Category 451 of 1000
Category 452 of 1000
Category 453 of 1000
Category 454 of 1000
Category 455 of 1000
Category 456 of 1000
Category 457 of 1000
Category 458 of 1000
Category 459 of 1000
Category 460 of 1000
Category 461 of 1000
Category 462 of 1000
Category 463 of 1000
Category 464 of 1000
Category 465 of 1000
Category 466 of 1000
Category 467 of 1000
Category 468 of 1000
Category 469 of 1000
Category 470 of 1000
Category 471 of 1000
Category 472 of 1000
Category 473 of 1000
Category 474 of 1000
Category 475 of 1000
Category 476 of 1000
Category 477 of 1000
Category 478 of 1000
Category 479 of 1000
Category 480 of 1000
Category 481 of 1000
Category 482 of 1000
Category 483 of 1000
Category 484 of 1000
Category 485 of 1000
Category 486 of 1000
Category 487 of 1000
Category 488 of 1000
Category 489 of 1000
Category 490 of 1000
Category 491 of 1000
Category 492 of 1000
Category 493 of 1000
Category 494 of 1000
Category 495 of 1000
Category 496 of 1000
Category 497 of 1000
Category 498 of 1000
Category 499 of 1000
Category 500 of 1000
Category 501 of 1000
Category 502 of 1000
Category 503 of 1000
Category 504 of 1000
Category 505 of 1000
Category 506 of 1000
Category 507 of 1000
Category 508 of 1000
Category 509 of 1000
Category 510 of 1000
Category 511 of 1000
Category 512 of 1000
Category 513 of 1000
Category 514 of 1000
Category 515 of 1000
Category 516 of 1000
Category 517 of 1000
Category 518 of 1000
Category 519 of 1000
Category 520 of 1000
Category 521 of 1000
Category 522 of 1000
Category 523 of 1000
Category 524 of 1000
Category 525 of 1000
Category 526 of 1000
Category 527 of 1000
Category 528 of 1000
Category 529 of 1000
Category 530 of 1000
Category 531 of 1000
Category 532 of 1000
Category 533 of 1000
Category 534 of 1000
Category 535 of 1000
Category 536 of 1000
Category 537 of 1000
Category 538 of 1000
Category 539 of 1000
Category 540 of 1000
Category 541 of 1000
Category 542 of 1000
Category 543 of 1000
Category 544 of 1000
Category 545 of 1000
Category 546 of 1000
Category 547 of 1000
Category 548 of 1000
Category 549 of 1000
Category 550 of 1000
Category 551 of 1000
Category 552 of 1000
Category 553 of 1000
Category 554 of 1000
Category 555 of 1000
Category 556 of 1000
Category 557 of 1000
Category 558 of 1000
Category 559 of 1000
Category 560 of 1000
Category 561 of 1000
Category 562 of 1000
Category 563 of 1000
Category 564 of 1000
Category 565 of 1000
Category 566 of 1000
Category 567 of 1000
Category 568 of 1000
Category 569 of 1000
Category 570 of 1000
Category 571 of 1000
Category 572 of 1000
Category 573 of 1000
Category 574 of 1000
Category 575 of 1000
Category 576 of 1000
Category 577 of 1000
Category 578 of 1000
Category 579 of 1000
Category 580 of 1000
Category 581 of 1000
Category 582 of 1000
Category 583 of 1000
Category 584 of 1000
Category 585 of 1000
Category 586 of 1000
Category 587 of 1000
Category 588 of 1000
Category 589 of 1000
Category 590 of 1000
Category 591 of 1000
Category 592 of 1000
Category 593 of 1000
Category 594 of 1000
Category 595 of 1000
Category 596 of 1000
Category 597 of 1000
Category 598 of 1000
Category 599 of 1000
Category 600 of 1000
Category 601 of 1000
Category 602 of 1000
Category 603 of 1000
Category 604 of 1000
Category 605 of 1000
Category 606 of 1000
Category 607 of 1000
Category 608 of 1000
Category 609 of 1000
Category 610 of 1000
Category 611 of 1000
Category 612 of 1000
Category 613 of 1000
Category 614 of 1000
Category 615 of 1000
Category 616 of 1000
Category 617 of 1000
Category 618 of 1000
Category 619 of 1000
Category 620 of 1000
Category 621 of 1000
Category 622 of 1000
Category 623 of 1000
Category 624 of 1000
Category 625 of 1000
Category 626 of 1000
Category 627 of 1000
Category 628 of 1000
Category 629 of 1000
Category 630 of 1000
Category 631 of 1000
Category 632 of 1000
Category 633 of 1000
Category 634 of 1000
Category 635 of 1000
Category 636 of 1000
Category 637 of 1000
Category 638 of 1000
Category 639 of 1000
Category 640 of 1000
Category 641 of 1000
Category 642 of 1000
Category 643 of 1000
Category 644 of 1000
Category 645 of 1000
Category 646 of 1000
Category 647 of 1000
Category 648 of 1000
Category 649 of 1000
Category 650 of 1000
Category 651 of 1000
Category 652 of 1000
Category 653 of 1000
Category 654 of 1000
Category 655 of 1000
Category 656 of 1000
Category 657 of 1000
Category 658 of 1000
Category 659 of 1000
Category 660 of 1000
Category 661 of 1000
Category 662 of 1000
Category 663 of 1000
Category 664 of 1000
Category 665 of 1000
Category 666 of 1000
Category 667 of 1000
Category 668 of 1000
Category 669 of 1000
Category 670 of 1000
Category 671 of 1000
Category 672 of 1000
Category 673 of 1000
Category 674 of 1000
Category 675 of 1000
Category 676 of 1000
Category 677 of 1000
Category 678 of 1000
Category 679 of 1000
Category 680 of 1000
Category 681 of 1000
Category 682 of 1000
Category 683 of 1000
Category 684 of 1000
Category 685 of 1000
Category 686 of 1000
Category 687 of 1000
Category 688 of 1000
Category 689 of 1000
Category 690 of 1000
Category 691 of 1000
Category 692 of 1000
Category 693 of 1000
Category 694 of 1000
Category 695 of 1000
Category 696 of 1000
Category 697 of 1000
Category 698 of 1000
Category 699 of 1000
Category 700 of 1000
Category 701 of 1000
Category 702 of 1000
Category 703 of 1000
Category 704 of 1000
Category 705 of 1000
Category 706 of 1000
Category 707 of 1000
Category 708 of 1000
Category 709 of 1000
Category 710 of 1000
Category 711 of 1000
Category 712 of 1000
Category 713 of 1000
Category 714 of 1000
Category 715 of 1000
Category 716 of 1000
Category 717 of 1000
Category 718 of 1000
Category 719 of 1000
Category 720 of 1000
Category 721 of 1000
Category 722 of 1000
Category 723 of 1000
Category 724 of 1000
Category 725 of 1000
Category 726 of 1000
Category 727 of 1000
Category 728 of 1000
Category 729 of 1000
Category 730 of 1000
Category 731 of 1000
Category 732 of 1000
Category 733 of 1000
Category 734 of 1000
Category 735 of 1000
Category 736 of 1000
Category 737 of 1000
Category 738 of 1000
Category 739 of 1000
Category 740 of 1000
Category 741 of 1000
Category 742 of 1000
Category 743 of 1000
Category 744 of 1000
Category 745 of 1000
Category 746 of 1000
Category 747 of 1000
Category 748 of 1000
Category 749 of 1000
Category 750 of 1000
Category 751 of 1000
Category 752 of 1000
Category 753 of 1000
Category 754 of 1000
Category 755 of 1000
Category 756 of 1000
Category 757 of 1000
Category 758 of 1000
Category 759 of 1000
Category 760 of 1000
Category 761 of 1000
Category 762 of 1000
Category 763 of 1000
Category 764 of 1000
Category 765 of 1000
Category 766 of 1000
Category 767 of 1000
Category 768 of 1000
Category 769 of 1000
Category 770 of 1000
Category 771 of 1000
Category 772 of 1000
Category 773 of 1000
Category 774 of 1000
Category 775 of 1000
Category 776 of 1000
Category 777 of 1000
Category 778 of 1000
Category 779 of 1000
Category 780 of 1000
Category 781 of 1000
Category 782 of 1000
Category 783 of 1000
Category 784 of 1000
Category 785 of 1000
Category 786 of 1000
Category 787 of 1000
Category 788 of 1000
Category 789 of 1000
Category 790 of 1000
Category 791 of 1000
Category 792 of 1000
Category 793 of 1000
Category 794 of 1000
Category 795 of 1000
Category 796 of 1000
Category 797 of 1000
Category 798 of 1000
Category 799 of 1000
Category 800 of 1000
Category 801 of 1000
Category 802 of 1000
Category 803 of 1000
Category 804 of 1000
Category 805 of 1000
Category 806 of 1000
Category 807 of 1000
Category 808 of 1000
Category 809 of 1000
Category 810 of 1000
Category 811 of 1000
Category 812 of 1000
Category 813 of 1000
Category 814 of 1000
Category 815 of 1000
Category 816 of 1000
Category 817 of 1000
Category 818 of 1000
Category 819 of 1000
Category 820 of 1000
Category 821 of 1000
Category 822 of 1000
Category 823 of 1000
Category 824 of 1000
Category 825 of 1000
Category 826 of 1000
Category 827 of 1000
Category 828 of 1000
Category 829 of 1000
Category 830 of 1000
Category 831 of 1000
Category 832 of 1000
Category 833 of 1000
Category 834 of 1000
Category 835 of 1000
Category 836 of 1000
Category 837 of 1000
Category 838 of 1000
Category 839 of 1000
Category 840 of 1000
Category 841 of 1000
Category 842 of 1000
Category 843 of 1000
Category 844 of 1000
Category 845 of 1000
Category 846 of 1000
Category 847 of 1000
Category 848 of 1000
Category 849 of 1000
Category 850 of 1000
Category 851 of 1000
Category 852 of 1000
Category 853 of 1000
Category 854 of 1000
Category 855 of 1000
Category 856 of 1000
Category 857 of 1000
Category 858 of 1000
Category 859 of 1000
Category 860 of 1000
Category 861 of 1000
Category 862 of 1000
Category 863 of 1000
Category 864 of 1000
Category 865 of 1000
Category 866 of 1000
Category 867 of 1000
Category 868 of 1000
Category 869 of 1000
Category 870 of 1000
Category 871 of 1000
Category 872 of 1000
Category 873 of 1000
Category 874 of 1000
Category 875 of 1000
Category 876 of 1000
Category 877 of 1000
Category 878 of 1000
Category 879 of 1000
Category 880 of 1000
Category 881 of 1000
Category 882 of 1000
Category 883 of 1000
Category 884 of 1000
Category 885 of 1000
Category 886 of 1000
Category 887 of 1000
Category 888 of 1000
Category 889 of 1000
Category 890 of 1000
Category 891 of 1000
Category 892 of 1000
Category 893 of 1000
Category 894 of 1000
Category 895 of 1000
Category 896 of 1000
Category 897 of 1000
Category 898 of 1000
Category 899 of 1000
Category 900 of 1000
Category 901 of 1000
Category 902 of 1000
Category 903 of 1000
Category 904 of 1000
Category 905 of 1000
Category 906 of 1000
Category 907 of 1000
Category 908 of 1000
Category 909 of 1000
Category 910 of 1000
Category 911 of 1000
Category 912 of 1000
Category 913 of 1000
Category 914 of 1000
Category 915 of 1000
Category 916 of 1000
Category 917 of 1000
Category 918 of 1000
Category 919 of 1000
Category 920 of 1000
Category 921 of 1000
Category 922 of 1000
Category 923 of 1000
Category 924 of 1000
Category 925 of 1000
Category 926 of 1000
Category 927 of 1000
Category 928 of 1000
Category 929 of 1000
Category 930 of 1000
Category 931 of 1000
Category 932 of 1000
Category 933 of 1000
Category 934 of 1000
Category 935 of 1000
Category 936 of 1000
Category 937 of 1000
Category 938 of 1000
Category 939 of 1000
Category 940 of 1000
Category 941 of 1000
Category 942 of 1000
Category 943 of 1000
Category 944 of 1000
Category 945 of 1000
Category 946 of 1000
Category 947 of 1000
Category 948 of 1000
Category 949 of 1000
Category 950 of 1000
Category 951 of 1000
Category 952 of 1000
Category 953 of 1000
Category 954 of 1000
Category 955 of 1000
Category 956 of 1000
Category 957 of 1000

In [166]:
books_cleaned

,title,category,price_gbp,price_display,availability,rating,product_url,image_url,source_website,source_page,scraped_at
0,A Light in the Attic,Poetry,51.77,£51.77,In Stock,3,https://books.toscrape.com/catalogue/a-light-i...,https://books.toscrape.com/media/cache/2c/da/2...,Books to Scrape,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00
1,Tipping the Velvet,Historical Fiction,53.74,£53.74,In Stock,1,https://books.toscrape.com/catalogue/tipping-t...,https://books.toscrape.com/media/cache/26/0c/2...,Books to Scrape,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00
2,Soumission,Fiction,50.1,£50.10,In Stock,1,https://books.toscrape.com/catalogue/soumissio...,https://books.toscrape.com/media/cache/3e/ef/3...,Books to Scrape,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00
3,Sharp Objects,Mystery,47.82,£47.82,In Stock,4,https://books.toscrape.com/catalogue/sharp-obj...,https://books.toscrape.com/media/cache/32/51/3...,Books to Scrape,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00
4,Sapiens: A Brief History of Humankind,History,54.23,£54.23,In Stock,5,https://books.toscrape.com/catalogue/sapiens-a...,https://books.toscrape.com/media/cache/be/a5/b...,Books to Scrape,https://books.toscrape.com/catalogue/page-1.html,2026-07-27 13:05:31.514892+00:00
...,...,...,...,...,...,...,...,...,...,...,...
995,Alice in Wonderland (Alice's Adventures in Won...,Classics,55.53,£55.53,In Stock,1,https://books.toscrape.com/catalogue/alice-in-...,https://books.toscrape.com/media/cache/96/ee/9...,Books to Scrape,https://books.toscrape.com/catalogue/page-50.html,2026-07-27 13:07:05.981122+00:00
996,"Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)",Sequential Art,57.06,£57.06,In Stock,4,https://books.toscrape.com/catalogue/ajin-demi...,https://books.toscrape.com/media/cache/09/7c/0...,Books to Scrape,https://books.toscrape.com/catalogue/page-50.html,2026-07-27 13:07:05.982122+00:00
997,A Spy's Devotion (The Regency Spies of London #1),Historical Fiction,16.97,£16.97,In Stock,5,https://books.toscrape.com/catalogue/a-spys-de...,https://books.toscrape.com/media/cache/1b/5f/1...,Books to Scrape,https://books.toscrape.com/catalogue/page-50.html,2026-07-27 13:07:05.982122+00:00
998,1st to Die (Women's Murder Club #1),Mystery,53.98,£53.98,In Stock,1,https://books.toscrape.com/catalogue/1st-to-di...,https://books.toscrape.com/media/cache/2b/41/2...,Books to Scrape,https://books.toscrape.com/catalogue/page-50.html,2026-07-27 13:07:05.982122+00:00
999,"1,000 Places to See Before You Die",Travel,26.08,£26.08,In Stock,5,https://books.toscrape.com/catalogue/1000-plac...,https://books.toscrape.com/media/cache/d7/0f/d...,Books to Scrape,https://books.toscrape.com/catalogue/page-50.html,2026-07-27 13:07:05.983122+00:00

In [169]:
books_cleaned.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title           1000 non-null   str
 1   category        1000 non-null   str
 2   price_gbp       1000 non-null   Float64
 3   price_display   1000 non-null   str
 4   availability    1000 non-null   string
 5   rating          1000 non-null   Int64
 6   product_url     1000 non-null   str
 7   image_url       1000 non-null   str
 8   source_website  1000 non-null   str
 9   source_page     1000 non-null   str
 10  scraped_at      1000 non-null   datetime64[us, UTC]
dtypes: Float64(1), Int64(1), datetime64[us, UTC](1), str(7), string(1)
memory usage: 88.0 KB